include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    unawaited_futures: true
    avoid_void_async: true
    unnecessary_await_in_return: true
    only_throw_errors: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cast_nullable_to_non_nullable: true
    use_colored_box: true
    use_decorated_box: true
    sized_box_shrink_expand: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    omit_local_variable_types: true
    directives_ordering: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_bool_literals_in_conditional_expressions: true
    prefer_single_quotes: true